[package]
name = "httpmock-wasi-test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
httpmock = { path = "..", default-features = false, features = ["wasm"] }
wasi-http-client = "0.2.1"
http = "1"
tokio = { version = "1", features = ["macros", "rt"] }
